In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'


In [2]:
import tensorflow as tf

In [3]:
x=tf.constant(4.0)
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
y=tf.constant([[1,2,3],[4,5,6]])
print(y.shape)

(2, 3)


In [4]:
x=tf.ones((3,3))
print(x)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [6]:
x=tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [7]:
x=tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [8]:
x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[ 0.5826625  -0.37781137 -0.574795  ]
 [-1.2398969   0.05530357  0.23875451]
 [ 1.2913601  -0.2253827  -0.8320221 ]], shape=(3, 3), dtype=float32)


In [9]:
x=tf.random.normal((3,3),mean=0,stddev=0)
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [10]:
x=tf.random.normal((3,3),mean=1,stddev=1)
print(x)

tf.Tensor(
[[-0.30914176  0.92543185  2.8867388 ]
 [ 1.6669161   1.2104468   0.33765882]
 [ 1.8626602   1.9668474   1.053649  ]], shape=(3, 3), dtype=float32)


In [11]:
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [12]:
x=tf.range(start=1,limit=10,delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [13]:
x=4.5
y=tf.cast(x,dtype=tf.float64)
print(y)

tf.Tensor(4.5, shape=(), dtype=float64)


In [15]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf

In [ ]:
#NUMERICAL OPERATIONS

In [16]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
z=tf.add(x,y)
print(z)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [17]:
z1=tf.subtract(x,y)
print(z1)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [19]:
z2=tf.divide(x,y)
print(z2)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [20]:
z3=tf.tensordot(x,y,axes=1)
print(z3)

tf.Tensor(46, shape=(), dtype=int32)


In [25]:
x1=tf.random.normal((2,3))
x2=tf.random.normal((3,6))
print(x1)
print(x2)


tf.Tensor(
[[ 2.62754   -1.2600309  1.390445 ]
 [ 1.3756189  0.4549234 -1.1096292]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.895294    0.512434    0.95601773 -0.498115    1.2020854  -0.3977576 ]
 [ 0.6235851   0.40896976  1.5808327   0.57981354 -1.8097448   0.05688135]
 [-0.91072845  0.94127387 -0.8346964  -0.97296655  3.0231683   1.6026627 ]], shape=(3, 6), dtype=float32)


In [26]:
z4=tf.matmul(x1,x2)
print(z4)

tf.Tensor(
[[ 0.3003664   2.139916   -0.6405225  -3.3922567   9.642411    1.111618  ]
 [ 2.5258377  -0.15350115  2.9604774   0.6581863  -2.5242796  -2.2996473 ]], shape=(2, 6), dtype=float32)


In [ ]:
#RAGGED MATRIX

In [30]:
import tensorflow as tf
ragged_data=[[1,2],
             [3,4,5],
             [6],
             [7,8,9,10]]
ragged_tensor=tf.ragged.constant(ragged_data)
print("Ragged Tensor:")
ragged_tensor

Ragged Tensor:


<tf.RaggedTensor [[1, 2], [3, 4, 5], [6], [7, 8, 9, 10]]>

In [ ]:
#SPARSE MATRIX

In [29]:
import tensorflow as tf
dense_data=[[0,0,3,0],
            [0,0,0,0],
            [0,2,0,0]]
sparse_tensor=tf.sparse.from_dense(dense_data)
print("Sparse Tensor:")
print(sparse_tensor)

Sparse Tensor:
SparseTensor(indices=tf.Tensor(
[[0 2]
 [2 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([3 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
